name: portfolio
services:
    portfolio:
        ports:
            - 3000:3000
        # Change this ğŸŒŸ
        # There's a list of commands for this, do later â€¼ï¸
        container_name: portfolio-container
        image: ghcr.io/womb0comb0/portfolio:main